backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "/media"

site_url: "/"
logo_url: "/media/logo.png"

collections:
  - name: "albums"
    label: "Albums"
    label_singular: "Album"
    folder: "content/albums"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug (URL id)", name: "slug", widget: "string", hint: "lowercase-dashes, e.g. steel-hall-brasov"}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "e.g. steel, rc, warehouse"}
      - {label: "Built Area (m²)", name: "area", widget: "number", required: false}
      - {label: "Steel Tonnage (t)", name: "steel", widget: "number", required: false}
      - {label: "Duration (months)", name: "duration", widget: "number", required: false}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
