backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "/media"

site_url: "/"
logo_url: "/media/logo.png"

collections:
  - name: "albums"
    label: "Albums"
    label_singular: "Album"
    folder: "content/albums"
    create: true
    format: "json"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
